name: Update COVID stats
on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update_stats:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: Run main
      id: python_script
      run: python nsw_api.py

    - name: Push to repo
      if: steps.python_script.outcome == 'success'
      run: |
        git diff
        git config --local user.email "technisculpt@users.noreply.github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update stats" || exit 0
        git push


    # run: python nsw_pdf.py pdfs no longer lists deaths
    # run: python nsw_website.py work in progress

    # - name: Install Node.js
    #   if: steps.python_script.outcome == 'success'
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    # - name: Install npm dependencies
    #   if: steps.python_script.outcome == 'success'
    #   run: |
    #     cd /path/to/your/react/app
    #     npm install

    # - name: Build and deploy React app
    #   if: steps.python_script.outcome == 'success'
    #   run: |
    #     cd /path/to/your/react/app
    #     npm run deploy
